version: "3.4"

services:
  db:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: pgredis
      POSTGRES_USER: pgredis
      POSTGRES_PASSWORD: fnord

  testdb:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: pgredis
      POSTGRES_USER: pgredis
      POSTGRES_PASSWORD: fnord

  psql:
    image: postgres:9.6
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: pgredis
      PGPASSWORD: fnord
      PGDATABASE: pgredis
    entrypoint: []
    command: ["psql"]

  dev:
    image: golang:1.13.1-buster
    depends_on:
      - db
    volumes:
      - .:/work
      - pgredis-mod:/go/pkg/mod/
    working_dir: /work
    command: bash
    ports:
      - "6379:6379"
    environment:
      GO111MODULE: "on"
      DATABASE_URL: "postgres://pgredis:fnord@db/pgredis?sslmode=disable"

  testserver:
    image: golang:1.13.1-buster
    depends_on:
      - testdb
    volumes:
      - .:/work
      - pgredis-mod:/go/pkg/mod/
    working_dir: /work
    command: "./scripts/run"
    ports:
      - "6379"
    environment:
      GO111MODULE: "on"
      DATABASE_URL: "postgres://pgredis:fnord@testdb/pgredis?sslmode=disable"

  testredis:
    image: redis:5.0.5
    ports:
      - "6379:6379"

  specs:
    image: ruby:2.6.3
    depends_on:
      - testserver
      - testredis
    volumes:
      - .:/work
      - ruby-2.6.3-gem-cache:/usr/local/bundle
      - ruby-tmp:/work/tmp
    working_dir: /work
    entrypoint: /work/scripts/bundle-exec
    command: bash
    environment:
      PGREDIS_URL: "redis://testserver"
      REALREDIS_URL: "redis://testredis"

volumes:
  pgredis-mod: ~
  ruby-2.6.3-gem-cache: ~
  ruby-tmp: ~
