#!/bin/bash -eu
#
# Operate in environment suitable for running go

cd $(dirname $0)/..

$(dirname $0)/psql psql -c "select encode(key, 'escape') as key, encode(type, 'escape') as type,encode(value, 'escape') as value, expires_at from redisdata order by key"
$(dirname $0)/psql psql -c "select encode(key, 'escape') as key, idx, encode(value, 'escape') as value from redislists order by key, idx"
$(dirname $0)/psql psql -c "select encode(key, 'escape') as key, encode(value, 'escape') as value from redissets order by key, value"
$(dirname $0)/psql psql -c "select encode(key, 'escape') as key, encode(value, 'escape') as value, score from rediszsets order by key, score, value"
